version: "3.9"
services: 
  cm-config-server: 
    hostname: "config-server"
    restart: always
    image: "geekymon2/cm-config-server"
    environment: 
      ARTIFACT_NAME: "config-server"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
      ENVIRONMENT: "${ENVIRONMENT}"
      CONFIG_SERVER_ENCRYPT_KEY: "${CONFIG_SERVER_ENCRYPT_KEY}"
    #local setup
    #container runs on port 8888
    #container exposing port 8888
    #container overrides APP_PORT and APP_PORT_CONTAINER when deployed
    ports:
      - "${APP_PORT:-8888}:${APP_PORT_CONTAINER:-8888}"