version: "3.9"
services: 
  cm-car-info-svc-web: 
    restart: always
    image: "geekymon2/cm-config-server"
    build: .
    environment: 
      ARTIFACT_NAME: "cm-config-server"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
      ENVIRONMENT: "${ENVIRONMENT}"
    #local setup
    #container runs on port 8888
    #container exposing port 8888
    #container overrides APP_PORT and APP_PORT_CONTAINER when deployed
    ports:
      - "${APP_PORT:-8888}:${APP_PORT_CONTAINER:-8888}"