server.port: 8888
spring.cloud.config.server.git:
          uri: C:/Users/manpr/Projects/GitHub/carmarketplace-config
          cloneOnStart: true
          defaultLabel: main
          searchPaths: '{application}'
logging.level.org.springframework.web: DEBUG