server.port: 8888
spring.cloud.config.server.git:
          uri: file://${M2}/Development/GeekyMon2/carmarketplace-config
          default-label: main
          searchPaths: '{application}/{application}-{profile}'          
logging.level.org.springframework.web: DEBUG