server.port: 8888
spring.cloud.config.server.git:
          uri: file://${M2}/Development/GeekyMon2/carmarketplace-config
          cloneOnStart: true
          defaultLabel: main
          searchPaths: '{application}'
logging.level.org.springframework.web: DEBUG