name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildservice:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: generate buildnumber
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}  
    - name: checkout root  
      uses: actions/checkout@v2
      with:
        repository: geekymon2/carmarketplace
        path: root
    - name: checkout service
      uses: actions/checkout@v2     
      with:
        path: service
    - name: load env
      uses: c-py/action-dotenv-to-setenv@v2
      with:
        env-file: service/.env 
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven 
    - name: build root
      run: mvn -N install --file root/pom.xml
    - name: build service
      run: mvn -B test package jacoco:report --file service/pom.xml -Dspring.profiles.active=test
    - name: Upload to codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: service/coverage/reports/
        verbose: true    
    - name: dockerhub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: push docker image
      uses: docker/build-push-action@v2
      with:
        context: ./service
        push: true
        tags: geekymon2/${{ env.IMAGE_NAME }}:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ steps.buildnumber.outputs.build_number }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          ARTIFACT_NAME=${{ env.ARTIFACT_NAME }}